import mongoose from 'mongoose';
import dotenv from 'dotenv';
import bcrypt from 'bcryptjs';

// Import All Models
import User from '../src/models/User.js';
import MemberProfile from '../src/models/MemberProfile.js';
import MembershipPlan from '../src/models/MembershipPlan.js';
import Membership from '../src/models/Membership.js';
import StaffProfile from '../src/models/StaffProfile.js';
import Shift from '../src/models/Shift.js';
import Attendance from '../src/models/Attendance.js';
import Leave from '../src/models/Leave.js';
import Payroll from '../src/models/Payroll.js';
import Court from '../src/models/Court.js';
import Booking from '../src/models/Booking.js';
import Product from '../src/models/Product.js';
import Order from '../src/models/Order.js';
import DiningTable from '../src/models/DiningTable.js';
import InventoryTransaction from '../src/models/InventoryTransaction.js';
import Payment from '../src/models/Payment.js';
import Invoice from '../src/models/Invoice.js';
import Expense from '../src/models/Expense.js';
import Lead from '../src/models/Lead.js';
import Task from '../src/models/Task.js';
import Project from '../src/models/Project.js';
import ClubSetting from '../src/models/ClubSetting.js';
import Notification from '../src/models/Notification.js';
import Activity from '../src/models/Activity.js';
import AuditLog from '../src/models/AuditLog.js';

dotenv.config();

const connectDB = async () => {
  const uri = process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/odoo_ldce_db';
  console.log(`Connecting to MongoDB (${uri.includes('mongodb.net') ? 'Atlas Cloud' : 'Local'})...`);
  await mongoose.connect(uri);
  console.log('MongoDB connection established successfully.');
};

const seedDatabase = async () => {
  try {
    await connectDB();
    console.log('⚡ Clearing all existing collections...');

    await Promise.all([
      User.deleteMany({}),
      MemberProfile.deleteMany({}),
      MembershipPlan.deleteMany({}),
      Membership.deleteMany({}),
      StaffProfile.deleteMany({}),
      Shift.deleteMany({}),
      Attendance.deleteMany({}),
      Leave.deleteMany({}),
      Payroll.deleteMany({}),
      Court.deleteMany({}),
      Booking.deleteMany({}),
      Product.deleteMany({}),
      Order.deleteMany({}),
      DiningTable.deleteMany({}),
      InventoryTransaction.deleteMany({}),
      Payment.deleteMany({}),
      Invoice.deleteMany({}),
      Expense.deleteMany({}),
      Lead.deleteMany({}),
      Task.deleteMany({}),
      Project.deleteMany({}),
      ClubSetting.deleteMany({}),
      Notification.deleteMany({}),
      Activity.deleteMany({}),
      AuditLog.deleteMany({}),
    ]);

    console.log('1. 👥 Creating Users & Password Hashes...');
    const salt = await bcrypt.genSalt(10);
    const ownerPass = await bcrypt.hash('Owner@123', salt);
    const staffPass = await bcrypt.hash('Staff@123', salt);
    const memberPass = await bcrypt.hash('Member@123', salt);

    const usersData = [
      // Owner / Club Manager
      {
        firstName: 'Amit',
        lastName: 'Patel',
        email: 'owner@championsclub.com',
        phone: '+91-9898000001',
        password: ownerPass,
        role: 'CLUB_MANAGER',
        department: null,
        status: 'ACTIVE',
        isEmailVerified: true,
        profileImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      },
      // Front Desk Staff
      {
        firstName: 'Rahul',
        lastName: 'Shah',
        email: 'frontdesk@championsclub.com',
        phone: '+91-9898000002',
        password: staffPass,
        role: 'STAFF',
        department: 'FRONT_DESK',
        status: 'ACTIVE',
        isEmailVerified: true,
        profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      },
      // Sports Shop Lead
      {
        firstName: 'Priya',
        lastName: 'Verma',
        email: 'shop@championsclub.com',
        phone: '+91-9898000003',
        password: staffPass,
        role: 'STAFF',
        department: 'SPORTS_SHOP',
        status: 'ACTIVE',
        isEmailVerified: true,
        profileImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
      },
      // Canteen & Cafe Lead
      {
        firstName: 'Vikram',
        lastName: 'Malhotra',
        email: 'canteen@championsclub.com',
        phone: '+91-9898000004',
        password: staffPass,
        role: 'STAFF',
        department: 'CANTEEN',
        status: 'ACTIVE',
        isEmailVerified: true,
        profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      },
      // Head Coach
      {
        firstName: 'Dharmesh',
        lastName: 'Rathod',
        email: 'coach.dharmesh@championsclub.com',
        phone: '+91-9898000005',
        password: staffPass,
        role: 'STAFF',
        department: 'FRONT_DESK',
        status: 'ACTIVE',
        isEmailVerified: true,
        profileImage: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
      },
      // Facilities Groundskeeper & Maintenance
      {
        firstName: 'Ramesh',
        lastName: 'Kaka',
        email: 'maintenance@championsclub.com',
        phone: '+91-9898000006',
        password: staffPass,
        role: 'STAFF',
        department: 'FRONT_DESK',
        status: 'ACTIVE',
        isEmailVerified: true,
        profileImage: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
      },

      // Members - Diverse Tiers & Situations
      // 1. Keni Patel (Gold - Active)
      {
        firstName: 'Keni',
        lastName: 'Patel',
        email: 'keni@championsclub.com',
        phone: '+91-9898000011',
        password: memberPass,
        role: 'MEMBER',
        status: 'ACTIVE',
        isEmailVerified: true,
        profileImage: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
      },
      // 2. Alex Morgan (Silver - Active)
      {
        firstName: 'Alex',
        lastName: 'Morgan',
        email: 'alex@championsclub.com',
        phone: '+91-9898000012',
        password: memberPass,
        role: 'MEMBER',
        status: 'ACTIVE',
        isEmailVerified: true,
        profileImage: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
      },
      // 3. Rohan Gupta (Junior Academy - Active)
      {
        firstName: 'Rohan',
        lastName: 'Gupta',
        email: 'junior@championsclub.com',
        phone: '+91-9898000013',
        password: memberPass,
        role: 'MEMBER',
        status: 'ACTIVE',
        isEmailVerified: true,
        profileImage: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
      },
      // 4. Meera Deshmukh (Platinum VIP - Active)
      {
        firstName: 'Meera',
        lastName: 'Deshmukh',
        email: 'meera.d@championsclub.com',
        phone: '+91-9898000014',
        password: memberPass,
        role: 'MEMBER',
        status: 'ACTIVE',
        isEmailVerified: true,
        profileImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      },
      // 5. Kabir Singhania (Corporate Gold - Active)
      {
        firstName: 'Kabir',
        lastName: 'Singhania',
        email: 'kabir.s@championsclub.com',
        phone: '+91-9898000015',
        password: memberPass,
        role: 'MEMBER',
        status: 'ACTIVE',
        isEmailVerified: true,
        profileImage: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150&auto=format&fit=crop&q=80',
      },
      // 6. Sara Mehta (Student Tier - Active)
      {
        firstName: 'Sara',
        lastName: 'Mehta',
        email: 'sara.m@championsclub.com',
        phone: '+91-9898000016',
        password: memberPass,
        role: 'MEMBER',
        status: 'ACTIVE',
        isEmailVerified: true,
        profileImage: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
      },
      // 7. Dr. Harshil Dave (Pending Subscription Settlement)
      {
        firstName: 'Harshil',
        lastName: 'Dave',
        email: 'harshil.d@championsclub.com',
        phone: '+91-9898000017',
        password: memberPass,
        role: 'MEMBER',
        status: 'ACTIVE',
        isEmailVerified: true,
        profileImage: 'https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=150&auto=format&fit=crop&q=80',
      },
      // 8. Siddharth Joshi (Expired Membership)
      {
        firstName: 'Siddharth',
        lastName: 'Joshi',
        email: 'siddharth.j@championsclub.com',
        phone: '+91-9898000018',
        password: memberPass,
        role: 'MEMBER',
        status: 'INACTIVE',
        isEmailVerified: true,
        profileImage: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
      },
      // 9. Ananya Roy (Family All-Access Tier - Active)
      {
        firstName: 'Ananya',
        lastName: 'Roy',
        email: 'ananya.r@championsclub.com',
        phone: '+91-9898000019',
        password: memberPass,
        role: 'MEMBER',
        status: 'ACTIVE',
        isEmailVerified: true,
        profileImage: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      },
    ];

    const users = await User.create(usersData);
    const [
      owner,
      frontDeskUser,
      shopUser,
      canteenUser,
      coachUser,
      maintUser,
      keniMember,
      alexMember,
      rohanMember,
      meeraMember,
      kabirMember,
      saraMember,
      harshilMember,
      siddharthMember,
      ananyaMember,
    ] = users;

    console.log('2. 📜 Creating Membership Plans (All Tiers)...');
    const plans = await MembershipPlan.create([
      {
        name: 'PLATINUM',
        targetUser: 'VIP & Executive Club Members',
        description: 'All-inclusive VIP tier: 100% complimentary court hours, 25% shop & cafe discount, highest booking priority, dedicated locker & personal coach.',
        price: 24000,
        duration: 365,
        durationInDays: 365,
        benefits: {
          courtDiscount: 100,
          shopDiscount: 25,
          cafeDiscount: 20,
          canteenDiscount: 20,
          bookingPriority: 'HIGH',
        },
        access: {
          courts: true,
          courtAccessType: 'ALL',
          shop: true,
          cafe: true,
          events: true,
          eventAccessType: 'ALL',
          training: true,
          trainingAccessType: 'PREMIUM',
          onlineShop: true,
          clubPickup: true,
          delivery: true,
        },
        courtDiscount: 100,
        shopDiscount: 25,
        canteenDiscount: 20,
        priorityBooking: true,
        fullCourtAccess: true,
        status: 'ACTIVE',
        isActive: true,
      },
      {
        name: 'GOLD',
        targetUser: 'Regular / Premium Enthusiasts',
        description: 'Complete club experience: all court access, 20% court discount, 15% shop & cafe discount, high booking priority, premium tournament entry.',
        price: 12000,
        duration: 365,
        durationInDays: 365,
        benefits: {
          courtDiscount: 20,
          shopDiscount: 15,
          cafeDiscount: 15,
          canteenDiscount: 15,
          bookingPriority: 'HIGH',
        },
        access: {
          courts: true,
          courtAccessType: 'ALL',
          shop: true,
          cafe: true,
          events: true,
          eventAccessType: 'ALL',
          training: true,
          trainingAccessType: 'PREMIUM',
          onlineShop: true,
          clubPickup: true,
          delivery: true,
        },
        courtDiscount: 20,
        shopDiscount: 15,
        canteenDiscount: 15,
        priorityBooking: true,
        fullCourtAccess: true,
        status: 'ACTIVE',
        isActive: true,
      },
      {
        name: 'SILVER',
        targetUser: 'Regular Recreational Players',
        description: 'Standard membership: 10% court discount, 10% shop discount, 5% cafe discount, standard booking priority, access to regular events.',
        price: 8000,
        duration: 365,
        durationInDays: 365,
        benefits: {
          courtDiscount: 10,
          shopDiscount: 10,
          cafeDiscount: 5,
          canteenDiscount: 5,
          bookingPriority: 'STANDARD',
        },
        access: {
          courts: true,
          courtAccessType: 'STANDARD',
          shop: true,
          cafe: true,
          events: true,
          eventAccessType: 'ALL',
          training: false,
          trainingAccessType: 'STANDARD',
          onlineShop: true,
          clubPickup: true,
          delivery: true,
        },
        courtDiscount: 10,
        shopDiscount: 10,
        canteenDiscount: 5,
        priorityBooking: false,
        fullCourtAccess: false,
        status: 'ACTIVE',
        isActive: true,
      },
      {
        name: 'JUNIOR',
        targetUser: 'Youth & Academy Under-18',
        description: 'Youth athlete tier: 15% court discount on junior courts, 10% shop & cafe discount, youth tournaments & dedicated academy coaching.',
        price: 5000,
        duration: 365,
        durationInDays: 365,
        benefits: {
          courtDiscount: 15,
          shopDiscount: 10,
          cafeDiscount: 10,
          canteenDiscount: 10,
          bookingPriority: 'STANDARD',
        },
        access: {
          courts: true,
          courtAccessType: 'JUNIOR',
          shop: true,
          cafe: true,
          events: true,
          eventAccessType: 'JUNIOR',
          training: true,
          trainingAccessType: 'JUNIOR',
          onlineShop: true,
          clubPickup: true,
          delivery: true,
        },
        courtDiscount: 15,
        shopDiscount: 10,
        canteenDiscount: 10,
        priorityBooking: false,
        fullCourtAccess: false,
        status: 'ACTIVE',
        isActive: true,
      },
      {
        name: 'FAMILY',
        targetUser: 'Family All-Inclusive (Up to 4)',
        description: 'All-access for entire household: 25% court discount across tennis, padel, badminton & cricket, 20% shop & cafe discount.',
        price: 35000,
        duration: 365,
        durationInDays: 365,
        benefits: {
          courtDiscount: 25,
          shopDiscount: 20,
          cafeDiscount: 20,
          canteenDiscount: 20,
          bookingPriority: 'HIGH',
        },
        access: {
          courts: true,
          courtAccessType: 'ALL',
          shop: true,
          cafe: true,
          events: true,
          eventAccessType: 'ALL',
          training: true,
          trainingAccessType: 'PREMIUM',
          onlineShop: true,
          clubPickup: true,
          delivery: true,
        },
        courtDiscount: 25,
        shopDiscount: 20,
        canteenDiscount: 20,
        priorityBooking: true,
        fullCourtAccess: true,
        status: 'ACTIVE',
        isActive: true,
      },
      {
        name: 'STUDENT',
        targetUser: 'College / University Athletes',
        description: 'Subsidized athlete tier: 15% court discount during off-peak hours (06:00 - 16:00), 10% cafe discounts.',
        price: 4500,
        duration: 180,
        durationInDays: 180,
        benefits: {
          courtDiscount: 15,
          shopDiscount: 10,
          cafeDiscount: 10,
          canteenDiscount: 10,
          bookingPriority: 'STANDARD',
        },
        access: {
          courts: true,
          courtAccessType: 'STANDARD',
          shop: true,
          cafe: true,
          events: true,
          eventAccessType: 'ALL',
          training: false,
          trainingAccessType: 'STANDARD',
          onlineShop: true,
          clubPickup: true,
          delivery: true,
        },
        courtDiscount: 15,
        shopDiscount: 10,
        canteenDiscount: 10,
        priorityBooking: false,
        fullCourtAccess: false,
        status: 'ACTIVE',
        isActive: true,
      },
    ]);

    const [platPlan, goldPlan, silverPlan, juniorPlan, familyPlan, studentPlan] = plans;

    console.log('3. 💳 Creating Member Profiles & Subscriptions Across Situations...');
    await MemberProfile.create([
      {
        user: keniMember._id,
        memberId: 'MEM-1001',
        gender: 'FEMALE',
        dateOfBirth: new Date('2001-05-15'),
        address: { street: '42 Club Drive, Bodakdev', city: 'Ahmedabad', state: 'Gujarat', pincode: '380054' },
        emergencyContact: { name: 'Sanjay Patel', phone: '+91-9898000099', relation: 'Father' },
        notes: 'Preferred court: Clay Tennis Center Court. Gold Member.',
      },
      {
        user: alexMember._id,
        memberId: 'MEM-1002',
        gender: 'MALE',
        dateOfBirth: new Date('1998-08-22'),
        address: { street: '18 Stadium Rd, Navrangpura', city: 'Ahmedabad', state: 'Gujarat', pincode: '380009' },
        emergencyContact: { name: 'Elena Morgan', phone: '+91-9898000098', relation: 'Spouse' },
        notes: 'Padel and Box Cricket regular. Enjoys sports lounge dining.',
      },
      {
        user: rohanMember._id,
        memberId: 'MEM-1003',
        gender: 'MALE',
        dateOfBirth: new Date('2008-11-10'),
        address: { street: '7 Park Avenue, Satellite', city: 'Ahmedabad', state: 'Gujarat', pincode: '380015' },
        emergencyContact: { name: 'Deepak Gupta', phone: '+91-9898000097', relation: 'Guardian' },
        notes: 'Junior Tennis Academy squad captain. Trains Mon/Wed/Fri.',
      },
      {
        user: meeraMember._id,
        memberId: 'MEM-1004',
        gender: 'FEMALE',
        dateOfBirth: new Date('1995-03-12'),
        address: { street: '104 Sunrise Heights, Prahladnagar', city: 'Ahmedabad', state: 'Gujarat', pincode: '380015' },
        emergencyContact: { name: 'Rajesh Deshmukh', phone: '+91-9898000096', relation: 'Brother' },
        notes: 'Badminton & Squash player. Platinum VIP member.',
      },
      {
        user: kabirMember._id,
        memberId: 'MEM-1005',
        gender: 'MALE',
        dateOfBirth: new Date('1992-12-05'),
        address: { street: '55 Sindhu Bhavan Rd', city: 'Ahmedabad', state: 'Gujarat', pincode: '380059' },
        emergencyContact: { name: 'Aarti Singhania', phone: '+91-9898000095', relation: 'Spouse' },
        notes: 'Corporate weekend turf league organizer.',
      },
      {
        user: saraMember._id,
        memberId: 'MEM-1006',
        gender: 'FEMALE',
        dateOfBirth: new Date('2004-09-18'),
        address: { street: '302 University Enclave, Vastrapur', city: 'Ahmedabad', state: 'Gujarat', pincode: '380015' },
        emergencyContact: { name: 'Dr. Vivek Mehta', phone: '+91-9898000094', relation: 'Father' },
        notes: 'College varsity badminton captain. Student tier.',
      },
      {
        user: harshilMember._id,
        memberId: 'MEM-1007',
        gender: 'MALE',
        dateOfBirth: new Date('1988-04-20'),
        address: { street: '21 Judges Bungalow Rd', city: 'Ahmedabad', state: 'Gujarat', pincode: '380054' },
        emergencyContact: { name: 'Nita Dave', phone: '+91-9898000093', relation: 'Spouse' },
        notes: 'Trial lead / Pending subscription settlement.',
      },
      {
        user: siddharthMember._id,
        memberId: 'MEM-1008',
        gender: 'MALE',
        dateOfBirth: new Date('1990-01-15'),
        address: { street: '88 Iscon Elegance', city: 'Ahmedabad', state: 'Gujarat', pincode: '380058' },
        emergencyContact: { name: 'Pooja Joshi', phone: '+91-9898000092', relation: 'Spouse' },
        notes: 'Previous Silver member (Expired on 31 Aug 2026). Renewal reminder queued.',
      },
      {
        user: ananyaMember._id,
        memberId: 'MEM-1009',
        gender: 'FEMALE',
        dateOfBirth: new Date('1987-07-30'),
        address: { street: '12 Ambli Greens', city: 'Ahmedabad', state: 'Gujarat', pincode: '380058' },
        emergencyContact: { name: 'Dev Roy', phone: '+91-9898000091', relation: 'Spouse' },
        notes: 'Family tier package (4 registered family passes).',
      },
    ]);

    const memberships = await Membership.create([
      // 1. Keni Patel - Past 2024 Silver Tier (Used / Expired)
      {
        member: keniMember._id,
        user: keniMember._id,
        plan: silverPlan._id,
        startDate: new Date('2024-01-01'),
        endDate: new Date('2024-12-31'),
        expiryDate: new Date('2024-12-31'),
        status: 'EXPIRED',
        paymentStatus: 'PAID',
        paymentMethod: 'UPI',
        amountPaid: silverPlan.price,
      },
      // 2. Keni Patel - Past 2025 Gold Tier (Used / Expired)
      {
        member: keniMember._id,
        user: keniMember._id,
        plan: goldPlan._id,
        startDate: new Date('2025-01-01'),
        endDate: new Date('2025-12-31'),
        expiryDate: new Date('2025-12-31'),
        status: 'EXPIRED',
        paymentStatus: 'PAID',
        paymentMethod: 'CARD',
        amountPaid: goldPlan.price,
      },
      // 3. Keni Patel - Current Active 2026 Gold Tier
      {
        member: keniMember._id,
        user: keniMember._id,
        plan: goldPlan._id,
        startDate: new Date('2026-01-01'),
        endDate: new Date('2027-01-01'),
        expiryDate: new Date('2027-01-01'),
        status: 'ACTIVE',
        paymentStatus: 'PAID',
        paymentMethod: 'UPI',
        amountPaid: goldPlan.price,
      },

      // 4. Meera Deshmukh - Past 2024 Gold Tier (Used / Expired)
      {
        member: meeraMember._id,
        user: meeraMember._id,
        plan: goldPlan._id,
        startDate: new Date('2024-01-01'),
        endDate: new Date('2024-12-31'),
        expiryDate: new Date('2024-12-31'),
        status: 'EXPIRED',
        paymentStatus: 'PAID',
        paymentMethod: 'UPI',
        amountPaid: goldPlan.price,
      },
      // 5. Meera Deshmukh - Past 2025 Platinum VIP (Used / Expired)
      {
        member: meeraMember._id,
        user: meeraMember._id,
        plan: platPlan._id,
        startDate: new Date('2025-01-01'),
        endDate: new Date('2025-12-31'),
        expiryDate: new Date('2025-12-31'),
        status: 'EXPIRED',
        paymentStatus: 'PAID',
        paymentMethod: 'CARD',
        amountPaid: platPlan.price,
      },
      // 6. Meera Deshmukh - Current Active 2026 Platinum VIP
      {
        member: meeraMember._id,
        user: meeraMember._id,
        plan: platPlan._id,
        startDate: new Date('2026-01-10'),
        endDate: new Date('2027-01-10'),
        expiryDate: new Date('2027-01-10'),
        status: 'ACTIVE',
        paymentStatus: 'PAID',
        paymentMethod: 'CARD',
        amountPaid: platPlan.price,
      },

      // 7. Alex Morgan - Past 2024 Student Tier (Used / Expired)
      {
        member: alexMember._id,
        user: alexMember._id,
        plan: studentPlan._id,
        startDate: new Date('2024-06-01'),
        endDate: new Date('2024-12-01'),
        expiryDate: new Date('2024-12-01'),
        status: 'EXPIRED',
        paymentStatus: 'PAID',
        paymentMethod: 'UPI',
        amountPaid: studentPlan.price,
      },
      // 8. Alex Morgan - Past 2025 Silver Tier (Used / Expired)
      {
        member: alexMember._id,
        user: alexMember._id,
        plan: silverPlan._id,
        startDate: new Date('2025-01-01'),
        endDate: new Date('2025-12-31'),
        expiryDate: new Date('2025-12-31'),
        status: 'EXPIRED',
        paymentStatus: 'PAID',
        paymentMethod: 'CARD',
        amountPaid: silverPlan.price,
      },
      // 9. Alex Morgan - Current Active 2026 Silver Tier
      {
        member: alexMember._id,
        user: alexMember._id,
        plan: silverPlan._id,
        startDate: new Date('2026-02-15'),
        endDate: new Date('2027-02-15'),
        expiryDate: new Date('2027-02-15'),
        status: 'ACTIVE',
        paymentStatus: 'PAID',
        paymentMethod: 'CARD',
        amountPaid: silverPlan.price,
      },

      // 10. Rohan Gupta - Past 2025 Junior Tier (Used / Expired)
      {
        member: rohanMember._id,
        user: rohanMember._id,
        plan: juniorPlan._id,
        startDate: new Date('2025-01-01'),
        endDate: new Date('2025-12-31'),
        expiryDate: new Date('2025-12-31'),
        status: 'EXPIRED',
        paymentStatus: 'PAID',
        paymentMethod: 'UPI',
        amountPaid: juniorPlan.price,
      },
      // 11. Rohan Gupta - Current Active 2026 Junior Tier
      {
        member: rohanMember._id,
        user: rohanMember._id,
        plan: juniorPlan._id,
        startDate: new Date('2026-03-01'),
        endDate: new Date('2027-03-01'),
        expiryDate: new Date('2027-03-01'),
        status: 'ACTIVE',
        paymentStatus: 'PAID',
        paymentMethod: 'UPI',
        amountPaid: juniorPlan.price,
      },

      // 12. Kabir Singhania - Past 2025 Silver Tier (Used / Expired)
      {
        member: kabirMember._id,
        user: kabirMember._id,
        plan: silverPlan._id,
        startDate: new Date('2025-01-01'),
        endDate: new Date('2025-12-31'),
        expiryDate: new Date('2025-12-31'),
        status: 'EXPIRED',
        paymentStatus: 'PAID',
        paymentMethod: 'UPI',
        amountPaid: silverPlan.price,
      },
      // 13. Kabir Singhania - Current Active 2026 Gold Tier
      {
        member: kabirMember._id,
        user: kabirMember._id,
        plan: goldPlan._id,
        startDate: new Date('2026-04-01'),
        endDate: new Date('2027-04-01'),
        expiryDate: new Date('2027-04-01'),
        status: 'ACTIVE',
        paymentStatus: 'PAID',
        paymentMethod: 'CARD',
        amountPaid: goldPlan.price,
      },

      // 14. Sara Mehta - Past 2025 Student Tier (Used / Expired)
      {
        member: saraMember._id,
        user: saraMember._id,
        plan: studentPlan._id,
        startDate: new Date('2025-06-01'),
        endDate: new Date('2025-12-01'),
        expiryDate: new Date('2025-12-01'),
        status: 'EXPIRED',
        paymentStatus: 'PAID',
        paymentMethod: 'UPI',
        amountPaid: studentPlan.price,
      },
      // 15. Sara Mehta - Current Active 2026 Student Tier
      {
        member: saraMember._id,
        user: saraMember._id,
        plan: studentPlan._id,
        startDate: new Date('2026-06-01'),
        endDate: new Date('2026-12-01'),
        expiryDate: new Date('2026-12-01'),
        status: 'ACTIVE',
        paymentStatus: 'PAID',
        paymentMethod: 'UPI',
        amountPaid: studentPlan.price,
      },

      // 16. Harshil Dave - Pending Subscription Settlement
      {
        member: harshilMember._id,
        user: harshilMember._id,
        plan: goldPlan._id,
        startDate: new Date(),
        endDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
        expiryDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
        status: 'SUSPENDED',
        paymentStatus: 'PENDING',
        paymentMethod: 'UPI',
        amountPaid: goldPlan.price,
      },

      // 17. Siddharth Joshi - Past 2024 Silver Tier (Used / Expired)
      {
        member: siddharthMember._id,
        user: siddharthMember._id,
        plan: silverPlan._id,
        startDate: new Date('2024-01-01'),
        endDate: new Date('2024-12-31'),
        expiryDate: new Date('2024-12-31'),
        status: 'EXPIRED',
        paymentStatus: 'PAID',
        paymentMethod: 'UPI',
        amountPaid: silverPlan.price,
      },
      // 18. Siddharth Joshi - Past 2025 Silver Tier (Used / Expired)
      {
        member: siddharthMember._id,
        user: siddharthMember._id,
        plan: silverPlan._id,
        startDate: new Date('2025-01-01'),
        endDate: new Date('2025-12-31'),
        expiryDate: new Date('2025-12-31'),
        status: 'EXPIRED',
        paymentStatus: 'PAID',
        paymentMethod: 'CARD',
        amountPaid: silverPlan.price,
      },
      // 19. Siddharth Joshi - Expired 2026 Silver Tier
      {
        member: siddharthMember._id,
        user: siddharthMember._id,
        plan: silverPlan._id,
        startDate: new Date('2025-08-31'),
        endDate: new Date('2026-08-31'),
        expiryDate: new Date('2026-08-31'),
        status: 'EXPIRED',
        paymentStatus: 'PAID',
        paymentMethod: 'UPI',
        amountPaid: silverPlan.price,
      },

      // 20. Ananya Roy - Past 2025 Family Tier (Used / Expired)
      {
        member: ananyaMember._id,
        user: ananyaMember._id,
        plan: familyPlan._id,
        startDate: new Date('2025-05-01'),
        endDate: new Date('2026-05-01'),
        expiryDate: new Date('2026-05-01'),
        status: 'EXPIRED',
        paymentStatus: 'PAID',
        paymentMethod: 'CARD',
        amountPaid: familyPlan.price,
      },
      // 21. Ananya Roy - Current Active 2026 Family Tier
      {
        member: ananyaMember._id,
        user: ananyaMember._id,
        plan: familyPlan._id,
        startDate: new Date('2026-05-01'),
        endDate: new Date('2027-05-01'),
        expiryDate: new Date('2027-05-01'),
        status: 'ACTIVE',
        paymentStatus: 'PAID',
        paymentMethod: 'CARD',
        amountPaid: familyPlan.price,
      },
    ]);

    console.log('4. 👔 Creating Staff Profiles Across Departments...');
    await StaffProfile.create([
      {
        user: frontDeskUser._id,
        employeeId: 'EMP-FD-101',
        department: 'FRONT_DESK',
        designation: 'Senior Receptionist & Court Coordinator',
        salary: 30000,
        joiningDate: new Date('2024-01-10'),
        employmentType: 'FULL_TIME',
        address: { street: '12 Green Park', city: 'Ahmedabad', state: 'Gujarat', pincode: '380052' },
        emergencyContact: { name: 'Pooja Shah', phone: '+91-9898111001', relation: 'Spouse' },
      },
      {
        user: shopUser._id,
        employeeId: 'EMP-SP-102',
        department: 'SPORTS_SHOP',
        designation: 'Pro Shop Inventory Manager',
        salary: 28000,
        joiningDate: new Date('2024-02-15'),
        employmentType: 'FULL_TIME',
        address: { street: '84 Royal Plaza', city: 'Ahmedabad', state: 'Gujarat', pincode: '380015' },
        emergencyContact: { name: 'Mahesh Verma', phone: '+91-9898111002', relation: 'Father' },
      },
      {
        user: canteenUser._id,
        employeeId: 'EMP-CN-103',
        department: 'CANTEEN',
        designation: 'Cafeteria & Sports Bar Lead Steward',
        salary: 26000,
        joiningDate: new Date('2024-03-01'),
        employmentType: 'FULL_TIME',
        address: { street: '307 River View', city: 'Ahmedabad', state: 'Gujarat', pincode: '380004' },
        emergencyContact: { name: 'Sunita Malhotra', phone: '+91-9898111003', relation: 'Mother' },
      },
      {
        user: coachUser._id,
        employeeId: 'EMP-CH-104',
        department: 'FRONT_DESK',
        designation: 'Head Tennis Coach & Tournament Director',
        salary: 48000,
        joiningDate: new Date('2023-11-01'),
        employmentType: 'FULL_TIME',
        address: { street: '51 Elite Enclave', city: 'Ahmedabad', state: 'Gujarat', pincode: '380058' },
        emergencyContact: { name: 'Geeta Rathod', phone: '+91-9898111004', relation: 'Spouse' },
      },
      {
        user: maintUser._id,
        employeeId: 'EMP-MN-105',
        department: 'FRONT_DESK',
        designation: 'Head Turf Groundskeeper & Facility Supervisor',
        salary: 24000,
        joiningDate: new Date('2023-08-01'),
        employmentType: 'FULL_TIME',
        address: { street: '14 Stadium Quarters', city: 'Ahmedabad', state: 'Gujarat', pincode: '380009' },
        emergencyContact: { name: 'Devji Kaka', phone: '+91-9898111005', relation: 'Brother' },
      },
    ]);

    const todayStart = new Date();
    todayStart.setHours(0, 0, 0, 0);

    const shifts = await Shift.create([
      {
        staff: frontDeskUser._id,
        date: todayStart,
        startTime: '06:00',
        endTime: '14:00',
        department: 'FRONT_DESK',
        status: 'SCHEDULED',
      },
      {
        staff: shopUser._id,
        date: todayStart,
        startTime: '10:00',
        endTime: '19:00',
        department: 'SPORTS_SHOP',
        status: 'SCHEDULED',
      },
      {
        staff: canteenUser._id,
        date: todayStart,
        startTime: '12:00',
        endTime: '22:00',
        department: 'CANTEEN',
        status: 'SCHEDULED',
      },
      {
        staff: coachUser._id,
        date: todayStart,
        startTime: '07:00',
        endTime: '16:00',
        department: 'FRONT_DESK',
        status: 'SCHEDULED',
      },
      {
        staff: maintUser._id,
        date: todayStart,
        startTime: '05:30',
        endTime: '13:30',
        department: 'FRONT_DESK',
        status: 'SCHEDULED',
      },
    ]);

    await Attendance.create([
      {
        staff: frontDeskUser._id,
        date: todayStart,
        shift: shifts[0]._id,
        checkInTime: '05:50 AM',
        status: 'PRESENT',
        notes: 'Morning court schedule verified and reception prepared.',
      },
      {
        staff: shopUser._id,
        date: todayStart,
        shift: shifts[1]._id,
        checkInTime: '09:55 AM',
        status: 'PRESENT',
        notes: 'Pro shop inventory audit and opening cash verified.',
      },
      {
        staff: canteenUser._id,
        date: todayStart,
        shift: shifts[2]._id,
        checkInTime: '11:50 AM',
        status: 'PRESENT',
        notes: 'Kitchen prep and bar restock completed.',
      },
      {
        staff: coachUser._id,
        date: todayStart,
        shift: shifts[3]._id,
        checkInTime: '06:50 AM',
        status: 'PRESENT',
        notes: 'Junior Tennis Academy morning training squad session.',
      },
      {
        staff: maintUser._id,
        date: todayStart,
        shift: shifts[4]._id,
        checkInTime: '05:25 AM',
        status: 'PRESENT',
        notes: 'Center clay court watering and line brushing.',
      },
    ]);

    await Leave.create([
      {
        staff: shopUser._id,
        startDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
        endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
        reason: 'Attending Wilson & Yonex sports gear supplier convention',
        status: 'PENDING',
      },
      {
        staff: canteenUser._id,
        startDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
        endDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
        reason: 'Personal family emergency',
        status: 'APPROVED',
        approvedBy: owner._id,
      },
      {
        staff: maintUser._id,
        startDate: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
        endDate: new Date(Date.now() + 16 * 24 * 60 * 60 * 1000),
        reason: 'Festival leave request',
        status: 'APPROVED',
        approvedBy: owner._id,
      },
    ]);

    await Payroll.create([
      {
        staff: frontDeskUser._id,
        monthYear: 'September 2026',
        basicSalary: 30000,
        bonus: 2500,
        deduction: 0,
        netSalary: 32500,
        status: 'PAID',
        paidDate: new Date('2026-09-30'),
        paymentMethod: 'BANK_TRANSFER',
        notes: 'September salary with customer service excellence award.',
      },
      {
        staff: shopUser._id,
        monthYear: 'September 2026',
        basicSalary: 28000,
        bonus: 2000,
        deduction: 0,
        netSalary: 30000,
        status: 'PAID',
        paidDate: new Date('2026-09-30'),
        paymentMethod: 'BANK_TRANSFER',
        notes: 'September salary with high POS gear sales volume incentive.',
      },
      {
        staff: canteenUser._id,
        monthYear: 'September 2026',
        basicSalary: 26000,
        bonus: 1500,
        deduction: 0,
        netSalary: 27500,
        status: 'PAID',
        paidDate: new Date('2026-09-30'),
        paymentMethod: 'BANK_TRANSFER',
        notes: 'September salary payout.',
      },
      {
        staff: coachUser._id,
        monthYear: 'September 2026',
        basicSalary: 48000,
        bonus: 5000,
        deduction: 0,
        netSalary: 53000,
        status: 'PAID',
        paidDate: new Date('2026-09-30'),
        paymentMethod: 'BANK_TRANSFER',
        notes: 'September coaching salary + tournament winning bonus.',
      },
      {
        staff: maintUser._id,
        monthYear: 'September 2026',
        basicSalary: 24000,
        bonus: 1000,
        deduction: 0,
        netSalary: 25000,
        status: 'PAID',
        paidDate: new Date('2026-09-30'),
        paymentMethod: 'BANK_TRANSFER',
        notes: 'September groundskeeper salary.',
      },
    ]);

    console.log('5. 🏟️ Creating Sports Courts Across Types...');
    const courts = await Court.create([
      {
        name: 'Center Court - Clay Tennis',
        type: 'TENNIS',
        hourlyRate: 600,
        walkInRate: 900,
        isIndoor: false,
        isActive: true,
        image: 'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?w=600&auto=format&fit=crop&q=80',
        description: 'Championship-grade Roland Garros red clay court with stadium lighting.',
      },
      {
        name: 'Court 2 - Synthetic Hard Tennis',
        type: 'TENNIS',
        hourlyRate: 750,
        walkInRate: 1100,
        isIndoor: true,
        isActive: true,
        image: 'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=600&auto=format&fit=crop&q=80',
        description: 'US Open blue cushioned acrylic hard court with climate control.',
      },
      {
        name: 'Padel Panoramic Court 1',
        type: 'PADEL',
        hourlyRate: 650,
        walkInRate: 950,
        isIndoor: false,
        isActive: true,
        image: 'https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=600&auto=format&fit=crop&q=80',
        description: 'Outdoor panoramic glass padel court with Mondo Supercourt turf.',
      },
      {
        name: 'Padel Glass Court 2',
        type: 'PADEL',
        hourlyRate: 700,
        walkInRate: 1000,
        isIndoor: true,
        isActive: true,
        image: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=600&auto=format&fit=crop&q=80',
        description: 'Indoor air-conditioned padel arena with pro LED lighting.',
      },
      {
        name: 'Floodlit Box Cricket Arena',
        type: 'CRICKET',
        hourlyRate: 1400,
        walkInRate: 1800,
        isIndoor: false,
        isActive: true,
        image: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=600&auto=format&fit=crop&q=80',
        description: 'High-density artificial turf with heavy-duty safety netting.',
      },
      {
        name: 'Teak Wood Badminton Court 1',
        type: 'BADMINTON',
        hourlyRate: 450,
        walkInRate: 650,
        isIndoor: true,
        isActive: true,
        image: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=600&auto=format&fit=crop&q=80',
        description: 'BWF-certified sprung teak wood court with anti-glare overhead lights.',
      },
      {
        name: 'Synthetic Mat Badminton Court 2',
        type: 'BADMINTON',
        hourlyRate: 400,
        walkInRate: 600,
        isIndoor: true,
        isActive: true,
        image: 'https://images.unsplash.com/photo-1521537634581-0dced2fee2ef?w=600&auto=format&fit=crop&q=80',
        description: 'Shock-absorbent Yonex synthetic mat badminton court.',
      },
      {
        name: 'All-Weather Cricket Pitch 2',
        type: 'CRICKET',
        hourlyRate: 1200,
        walkInRate: 1600,
        isIndoor: false,
        isActive: true,
        image: 'https://images.unsplash.com/photo-1531415074868-036b1c57e3ce?w=600&auto=format&fit=crop&q=80',
        description: 'Multi-lane bowling nets and full size synthetic turf pitch.',
      },
    ]);

    console.log('6. 📅 Creating Court Bookings in All Situations (Completed, Playing, Confirmed, Cancelled)...');
    const bookings = await Booking.create([
      // ==========================================
      // A. HISTORICAL PAST BOOKINGS (COMPLETED)
      // ==========================================
      // 1. Keni Patel - Clay Tennis (30 days ago)
      {
        court: courts[0]._id,
        member: keniMember._id,
        bookingType: 'MEMBER',
        bookingSource: 'ONLINE',
        date: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
        startTime: '07:00',
        endTime: '08:00',
        durationMinutes: 60,
        price: courts[0].hourlyRate,
        discountApplied: 120, // Gold 20%
        finalAmount: 480,
        paymentMethod: 'UPI',
        paymentStatus: 'PAID',
        status: 'COMPLETED',
        checkInTime: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000 + 7 * 3600000),
        checkOutTime: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000 + 8 * 3600000),
        bookedBy: keniMember._id,
      },
      // 2. Keni Patel - Teakwood Badminton (14 days ago)
      {
        court: courts[5]._id,
        member: keniMember._id,
        bookingType: 'MEMBER',
        bookingSource: 'ONLINE',
        date: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
        startTime: '18:00',
        endTime: '19:00',
        durationMinutes: 60,
        price: courts[5].hourlyRate,
        discountApplied: 90, // Gold 20%
        finalAmount: 360,
        paymentMethod: 'UPI',
        paymentStatus: 'PAID',
        status: 'COMPLETED',
        checkInTime: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000 + 18 * 3600000),
        checkOutTime: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000 + 19 * 3600000),
        bookedBy: keniMember._id,
      },
      // 3. Keni Patel - Padel Panoramic 1 (7 days ago)
      {
        court: courts[2]._id,
        member: keniMember._id,
        bookingType: 'MEMBER',
        bookingSource: 'ONLINE',
        date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
        startTime: '19:00',
        endTime: '20:00',
        durationMinutes: 60,
        price: courts[2].hourlyRate,
        discountApplied: 130, // Gold 20%
        finalAmount: 520,
        paymentMethod: 'UPI',
        paymentStatus: 'PAID',
        status: 'COMPLETED',
        checkInTime: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000 + 19 * 3600000),
        checkOutTime: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000 + 20 * 3600000),
        bookedBy: keniMember._id,
      },
      // 4. Meera Deshmukh - Synthetic Hard Tennis 2 (21 days ago, Platinum VIP 100% Free)
      {
        court: courts[1]._id,
        member: meeraMember._id,
        bookingType: 'MEMBER',
        bookingSource: 'ONLINE',
        date: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000),
        startTime: '08:00',
        endTime: '09:30',
        durationMinutes: 90,
        price: 1125,
        discountApplied: 1125, // VIP 100%
        finalAmount: 0,
        paymentMethod: 'MEMBERSHIP_INCLUDED',
        paymentStatus: 'PAID',
        status: 'COMPLETED',
        checkInTime: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000 + 8 * 3600000),
        checkOutTime: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000 + 9.5 * 3600000),
        bookedBy: meeraMember._id,
      },
      // 5. Meera Deshmukh - Synthetic Mat Badminton (7 days ago, Platinum VIP)
      {
        court: courts[6]._id,
        member: meeraMember._id,
        bookingType: 'MEMBER',
        bookingSource: 'ONLINE',
        date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
        startTime: '17:00',
        endTime: '18:00',
        durationMinutes: 60,
        price: courts[6].hourlyRate,
        discountApplied: courts[6].hourlyRate,
        finalAmount: 0,
        paymentMethod: 'MEMBERSHIP_INCLUDED',
        paymentStatus: 'PAID',
        status: 'COMPLETED',
        checkInTime: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000 + 17 * 3600000),
        checkOutTime: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000 + 18 * 3600000),
        bookedBy: meeraMember._id,
      },
      // 6. Alex Morgan - Floodlit Box Cricket (10 days ago)
      {
        court: courts[4]._id,
        member: alexMember._id,
        bookingType: 'MEMBER',
        bookingSource: 'ONLINE',
        date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
        startTime: '19:00',
        endTime: '21:00',
        durationMinutes: 120,
        price: 2800,
        discountApplied: 280, // Silver 10%
        finalAmount: 2520,
        paymentMethod: 'CARD',
        paymentStatus: 'PAID',
        status: 'COMPLETED',
        checkInTime: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000 + 19 * 3600000),
        checkOutTime: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000 + 21 * 3600000),
        bookedBy: alexMember._id,
      },
      // 7. Alex Morgan - Padel Glass Court 2 (5 days ago)
      {
        court: courts[3]._id,
        member: alexMember._id,
        bookingType: 'MEMBER',
        bookingSource: 'ONLINE',
        date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
        startTime: '17:00',
        endTime: '18:00',
        durationMinutes: 60,
        price: courts[3].hourlyRate,
        discountApplied: 70, // Silver 10%
        finalAmount: 630,
        paymentMethod: 'UPI',
        paymentStatus: 'PAID',
        status: 'COMPLETED',
        checkInTime: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000 + 17 * 3600000),
        checkOutTime: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000 + 18 * 3600000),
        bookedBy: alexMember._id,
      },
      // 8. Rohan Gupta - Junior Center Clay Tennis (3 days ago)
      {
        court: courts[0]._id,
        member: rohanMember._id,
        bookingType: 'MEMBER',
        bookingSource: 'ONLINE',
        date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
        startTime: '06:30',
        endTime: '07:30',
        durationMinutes: 60,
        price: courts[0].hourlyRate,
        discountApplied: 90, // Junior 15%
        finalAmount: 510,
        paymentMethod: 'UPI',
        paymentStatus: 'PAID',
        status: 'COMPLETED',
        checkInTime: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000 + 6.5 * 3600000),
        checkOutTime: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000 + 7.5 * 3600000),
        bookedBy: rohanMember._id,
      },
      // 9. Kabir Singhania - Box Cricket Arena (Last Sunday)
      {
        court: courts[4]._id,
        member: kabirMember._id,
        bookingType: 'MEMBER',
        bookingSource: 'ONLINE',
        date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
        startTime: '18:00',
        endTime: '20:00',
        durationMinutes: 120,
        price: 2800,
        discountApplied: 560, // Gold 20%
        finalAmount: 2240,
        paymentMethod: 'CARD',
        paymentStatus: 'PAID',
        status: 'COMPLETED',
        checkInTime: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000 + 18 * 3600000),
        checkOutTime: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000 + 20 * 3600000),
        bookedBy: kabirMember._id,
      },
      // 10. Sara Mehta - Teak Wood Badminton (2 days ago)
      {
        court: courts[5]._id,
        member: saraMember._id,
        bookingType: 'MEMBER',
        bookingSource: 'ONLINE',
        date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
        startTime: '07:00',
        endTime: '08:00',
        durationMinutes: 60,
        price: courts[5].hourlyRate,
        discountApplied: 45, // Student 10%
        finalAmount: 405,
        paymentMethod: 'UPI',
        paymentStatus: 'PAID',
        status: 'COMPLETED',
        checkInTime: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 7 * 3600000),
        checkOutTime: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 8 * 3600000),
        bookedBy: saraMember._id,
      },
      // 11. Walk-in Guest (Nitin Shah) - Hard Tennis 2 (4 days ago)
      {
        court: courts[1]._id,
        bookingType: 'WALK_IN',
        bookingSource: 'FRONT_DESK',
        walkInDetails: { name: 'Nitin Shah', phone: '+91-9879001122', email: 'nitin.shah@gmail.com' },
        date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
        startTime: '16:00',
        endTime: '17:00',
        durationMinutes: 60,
        price: courts[1].walkInRate,
        discountApplied: 0,
        finalAmount: courts[1].walkInRate,
        paymentMethod: 'CASH',
        paymentStatus: 'PAID',
        status: 'COMPLETED',
        checkInTime: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000 + 16 * 3600000),
        checkOutTime: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000 + 17 * 3600000),
        bookedBy: frontDeskUser._id,
      },

      // ==========================================
      // B. TODAY'S BOOKINGS (VARIOUS SITUATIONS)
      // ==========================================
      // 12. Center Court Clay - Completed Morning Slot (Keni Patel)
      {
        court: courts[0]._id,
        member: keniMember._id,
        bookingType: 'MEMBER',
        bookingSource: 'ONLINE',
        date: todayStart,
        startTime: '07:00',
        endTime: '08:00',
        durationMinutes: 60,
        price: courts[0].hourlyRate,
        discountApplied: 120, // Gold 20%
        finalAmount: 480,
        paymentMethod: 'UPI',
        paymentStatus: 'PAID',
        status: 'COMPLETED',
        checkInTime: new Date(todayStart.getTime() + 7 * 60 * 60 * 1000),
        checkOutTime: new Date(todayStart.getTime() + 8 * 60 * 60 * 1000),
        bookedBy: keniMember._id,
      },
      // 13. Court 2 Hard Tennis - Checked In Live (Meera Deshmukh VIP 100% Free)
      {
        court: courts[1]._id,
        member: meeraMember._id,
        bookingType: 'MEMBER',
        bookingSource: 'FRONT_DESK',
        date: todayStart,
        startTime: '09:00',
        endTime: '10:00',
        durationMinutes: 60,
        price: courts[1].hourlyRate,
        discountApplied: courts[1].hourlyRate,
        finalAmount: 0,
        paymentMethod: 'MEMBERSHIP_INCLUDED',
        paymentStatus: 'PAID',
        status: 'CHECKED_IN',
        checkInTime: new Date(todayStart.getTime() + 9 * 60 * 60 * 1000),
        bookedBy: frontDeskUser._id,
      },
      // 14. Padel Panoramic Court 1 - Confirmed Evening Match (Alex Morgan)
      {
        court: courts[2]._id,
        member: alexMember._id,
        bookingType: 'MEMBER',
        bookingSource: 'ONLINE',
        date: todayStart,
        startTime: '18:00',
        endTime: '19:00',
        durationMinutes: 60,
        price: courts[2].hourlyRate,
        discountApplied: 65, // Silver 10%
        finalAmount: 585,
        paymentMethod: 'UPI',
        paymentStatus: 'PAID',
        status: 'CONFIRMED',
        bookedBy: alexMember._id,
      },
      // 15. Box Cricket Arena - Walk-in Tonight Confirmed (Sameer Desai)
      {
        court: courts[4]._id,
        bookingType: 'WALK_IN',
        bookingSource: 'FRONT_DESK',
        walkInDetails: { name: 'Sameer Desai', phone: '+91-9922001122', email: 'sameer.d@gmail.com' },
        date: todayStart,
        startTime: '19:00',
        endTime: '20:00',
        durationMinutes: 60,
        price: courts[4].walkInRate,
        discountApplied: 0,
        finalAmount: courts[4].walkInRate,
        paymentMethod: 'CARD',
        paymentStatus: 'PAID',
        status: 'CONFIRMED',
        bookedBy: frontDeskUser._id,
      },
      // 16. Badminton Court 1 - Phone Booking Confirmed (Dr. Harshil Shah)
      {
        court: courts[5]._id,
        bookingType: 'PHONE',
        bookingSource: 'PHONE',
        walkInDetails: { name: 'Dr. Harshil Shah', phone: '+91-9825012345', email: 'harshil.ortho@gmail.com' },
        date: todayStart,
        startTime: '17:00',
        endTime: '18:00',
        durationMinutes: 60,
        price: courts[5].walkInRate,
        discountApplied: 0,
        finalAmount: courts[5].walkInRate,
        paymentMethod: 'CASH',
        paymentStatus: 'PAID',
        status: 'CONFIRMED',
        bookedBy: frontDeskUser._id,
      },
      // 17. Center Court Clay - Confirmed Night Slot (Keni Patel - 2nd Booking today!)
      {
        court: courts[0]._id,
        member: keniMember._id,
        bookingType: 'MEMBER',
        bookingSource: 'ONLINE',
        date: todayStart,
        startTime: '20:00',
        endTime: '21:00',
        durationMinutes: 60,
        price: courts[0].hourlyRate,
        discountApplied: 120,
        finalAmount: 480,
        paymentMethod: 'UPI',
        paymentStatus: 'PAID',
        status: 'CONFIRMED',
        bookedBy: keniMember._id,
      },
      // 18. Padel Glass Court 2 - Cancelled with Refund Logged (Kabir Singhania)
      {
        court: courts[3]._id,
        member: kabirMember._id,
        bookingType: 'MEMBER',
        bookingSource: 'ONLINE',
        date: todayStart,
        startTime: '16:00',
        endTime: '17:00',
        durationMinutes: 60,
        price: courts[3].hourlyRate,
        discountApplied: 140,
        finalAmount: 560,
        paymentMethod: 'UPI',
        paymentStatus: 'REFUNDED',
        status: 'CANCELLED',
        cancellationReason: 'Rain in travel corridor; slot released.',
        bookedBy: kabirMember._id,
      },
      // 19. Synthetic Mat Badminton Court 2 - Confirmed Junior Slot (Rohan Gupta)
      {
        court: courts[6]._id,
        member: rohanMember._id,
        bookingType: 'MEMBER',
        bookingSource: 'ONLINE',
        date: todayStart,
        startTime: '16:00',
        endTime: '17:00',
        durationMinutes: 60,
        price: courts[6].hourlyRate,
        discountApplied: 60, // Junior 15%
        finalAmount: 340,
        paymentMethod: 'UPI',
        paymentStatus: 'PAID',
        status: 'CONFIRMED',
        bookedBy: rohanMember._id,
      },
      // 20. Teak Wood Badminton Court 1 - Confirmed Student Slot (Sara Mehta)
      {
        court: courts[5]._id,
        member: saraMember._id,
        bookingType: 'MEMBER',
        bookingSource: 'ONLINE',
        date: todayStart,
        startTime: '14:00',
        endTime: '15:00',
        durationMinutes: 60,
        price: courts[5].hourlyRate,
        discountApplied: 45, // Student 10%
        finalAmount: 405,
        paymentMethod: 'UPI',
        paymentStatus: 'PAID',
        status: 'CONFIRMED',
        bookedBy: saraMember._id,
      },
      // 21. Synthetic Mat Badminton Court 2 - Pending Payment Hold (Harshil Dave)
      {
        court: courts[6]._id,
        member: harshilMember._id,
        bookingType: 'MEMBER',
        bookingSource: 'FRONT_DESK',
        date: todayStart,
        startTime: '18:00',
        endTime: '19:00',
        durationMinutes: 60,
        price: courts[6].hourlyRate,
        discountApplied: 0,
        finalAmount: courts[6].hourlyRate,
        paymentMethod: 'UPI',
        paymentStatus: 'PENDING',
        status: 'PENDING',
        bookedBy: frontDeskUser._id,
      },

      // ==========================================
      // C. UPCOMING FUTURE BOOKINGS (TOMORROW & NEXT WEEK)
      // ==========================================
      // 22. All-Weather Cricket Turf - Family Weekend Match (Ananya Roy)
      {
        court: courts[7]._id,
        member: ananyaMember._id,
        bookingType: 'MEMBER',
        bookingSource: 'ONLINE',
        date: new Date(Date.now() + 24 * 60 * 60 * 1000),
        startTime: '10:00',
        endTime: '12:00',
        durationMinutes: 120,
        price: 2400,
        discountApplied: 600, // Family 25%
        finalAmount: 1800,
        paymentMethod: 'CARD',
        paymentStatus: 'PAID',
        status: 'CONFIRMED',
        bookedBy: ananyaMember._id,
      },
      // 23. Synthetic Hard Tennis 2 - Tomorrow Morning (Keni Patel)
      {
        court: courts[1]._id,
        member: keniMember._id,
        bookingType: 'MEMBER',
        bookingSource: 'ONLINE',
        date: new Date(Date.now() + 24 * 60 * 60 * 1000),
        startTime: '08:00',
        endTime: '09:00',
        durationMinutes: 60,
        price: courts[1].hourlyRate,
        discountApplied: 150, // Gold 20%
        finalAmount: 600,
        paymentMethod: 'UPI',
        paymentStatus: 'PAID',
        status: 'CONFIRMED',
        bookedBy: keniMember._id,
      },
      // 24. Padel Panoramic Court 1 - Tomorrow Evening (Keni Patel)
      {
        court: courts[2]._id,
        member: keniMember._id,
        bookingType: 'MEMBER',
        bookingSource: 'ONLINE',
        date: new Date(Date.now() + 24 * 60 * 60 * 1000),
        startTime: '19:00',
        endTime: '20:00',
        durationMinutes: 60,
        price: courts[2].hourlyRate,
        discountApplied: 130, // Gold 20%
        finalAmount: 520,
        paymentMethod: 'UPI',
        paymentStatus: 'PAID',
        status: 'CONFIRMED',
        bookedBy: keniMember._id,
      },
      // 25. Center Court Clay - Tomorrow Morning VIP (Meera Deshmukh)
      {
        court: courts[0]._id,
        member: meeraMember._id,
        bookingType: 'MEMBER',
        bookingSource: 'ONLINE',
        date: new Date(Date.now() + 24 * 60 * 60 * 1000),
        startTime: '07:00',
        endTime: '08:30',
        durationMinutes: 90,
        price: 900,
        discountApplied: 900, // VIP 100% Free
        finalAmount: 0,
        paymentMethod: 'MEMBERSHIP_INCLUDED',
        paymentStatus: 'PAID',
        status: 'CONFIRMED',
        bookedBy: meeraMember._id,
      },
      // 26. Teak Wood Badminton Court 1 - Saturday Morning Academy (Rohan Gupta)
      {
        court: courts[5]._id,
        member: rohanMember._id,
        bookingType: 'MEMBER',
        bookingSource: 'ONLINE',
        date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
        startTime: '10:00',
        endTime: '11:00',
        durationMinutes: 60,
        price: courts[5].hourlyRate,
        discountApplied: 67.5, // Junior 15%
        finalAmount: 382.5,
        paymentMethod: 'UPI',
        paymentStatus: 'PAID',
        status: 'CONFIRMED',
        bookedBy: rohanMember._id,
      },
      // 27. Floodlit Box Cricket Arena - Saturday Night Match (Alex Morgan)
      {
        court: courts[4]._id,
        member: alexMember._id,
        bookingType: 'MEMBER',
        bookingSource: 'ONLINE',
        date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
        startTime: '18:00',
        endTime: '20:00',
        durationMinutes: 120,
        price: 2800,
        discountApplied: 280, // Silver 10%
        finalAmount: 2520,
        paymentMethod: 'CARD',
        paymentStatus: 'PAID',
        status: 'CONFIRMED',
        bookedBy: alexMember._id,
      },
      // 28. Teak Wood Badminton Court 1 - Sunday Training (Sara Mehta)
      {
        court: courts[5]._id,
        member: saraMember._id,
        bookingType: 'MEMBER',
        bookingSource: 'ONLINE',
        date: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
        startTime: '09:00',
        endTime: '10:30',
        durationMinutes: 90,
        price: 675,
        discountApplied: 67.5, // Student 10%
        finalAmount: 607.5,
        paymentMethod: 'UPI',
        paymentStatus: 'PAID',
        status: 'CONFIRMED',
        bookedBy: saraMember._id,
      },
      // 29. Padel Glass Court 2 - Next Monday Evening Walk-in (Vikram Shah)
      {
        court: courts[3]._id,
        bookingType: 'WALK_IN',
        bookingSource: 'FRONT_DESK',
        walkInDetails: { name: 'Vikram Shah', phone: '+91-9898007711', email: 'vikram.shah@gmail.com' },
        date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
        startTime: '18:00',
        endTime: '19:00',
        durationMinutes: 60,
        price: courts[3].walkInRate,
        discountApplied: 0,
        finalAmount: courts[3].walkInRate,
        paymentMethod: 'CASH',
        paymentStatus: 'PAID',
        status: 'CONFIRMED',
        bookedBy: frontDeskUser._id,
      },
    ]);

    console.log('7. 🏷️ Creating Sports Gear & Canteen Products...');
    const products = await Product.create([
      // Sports Pro Shop Catalog
      {
        name: 'Wilson Pro Staff 97 v14 Tennis Racket',
        type: 'sports',
        category: 'Rackets',
        sku: 'WIL-PS97-V14',
        brand: 'Wilson',
        price: 18500,
        stock: 6,
        lowStockThreshold: 3,
        isAvailable: true,
        image: 'https://images.unsplash.com/photo-1617083934555-563d4206e236?w=400&auto=format&fit=crop&q=80',
        description: 'Precision weapon engineered for competitive players with Braided 45 construction.',
      },
      {
        name: 'Wilson US Open Championship Tennis Balls (Can of 3)',
        type: 'sports',
        category: 'Balls',
        sku: 'WIL-USO-3B',
        brand: 'Wilson',
        price: 450,
        stock: 150,
        lowStockThreshold: 25,
        isAvailable: true,
        image: 'https://images.unsplash.com/photo-1587280501635-68a0e82cd5ff?w=400&auto=format&fit=crop&q=80',
        description: 'Official ball of the US Open with premium Tex/Tech Industries felt.',
      },
      {
        name: 'Nike Court Air Zoom Vapor Pro 2 Shoes',
        type: 'sports',
        category: 'Shoes',
        sku: 'NKE-VPR-PRO2',
        brand: 'Nike',
        price: 8900,
        stock: 12,
        lowStockThreshold: 4,
        isAvailable: true,
        image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&auto=format&fit=crop&q=80',
        description: 'Lightweight court shoes with Zoom Air cushioning and herringbone outsole.',
      },
      {
        name: 'Babolat Pure Aero Super Tour 9 Racket Bag',
        type: 'sports',
        category: 'Bags',
        sku: 'BAB-PA-TOUR9',
        brand: 'Babolat',
        price: 6500,
        stock: 8,
        lowStockThreshold: 3,
        isAvailable: true,
        image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&auto=format&fit=crop&q=80',
        description: 'Thermal insulated compartments to hold up to 9 rackets and accessories.',
      },
      {
        name: 'Yonex BG65 Titanium Badminton String Reel (200m)',
        type: 'sports',
        category: 'Accessories',
        sku: 'YNX-BG65-TI',
        brand: 'Yonex',
        price: 4200,
        stock: 18,
        lowStockThreshold: 5,
        isAvailable: true,
        image: 'https://images.unsplash.com/photo-1584824486509-112e4181ff6b?w=400&auto=format&fit=crop&q=80',
        description: 'Compound titanium hydride coating for sharp hitting feel and durability.',
      },
      {
        name: 'Bullpadel Vertex 04 Padel Racket 2026',
        type: 'sports',
        category: 'Rackets',
        sku: 'BUL-VTX-04',
        brand: 'Bullpadel',
        price: 22000,
        stock: 2, // Low stock trigger
        lowStockThreshold: 3,
        isAvailable: true,
        image: 'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=400&auto=format&fit=crop&q=80',
        description: 'Diamond shaped diamond power racket with Xtend Carbon 12K surface.',
      },
      {
        name: 'Yonex Astrox 99 Pro Badminton Racket',
        type: 'sports',
        category: 'Rackets',
        sku: 'YNX-AX99-PRO',
        brand: 'Yonex',
        price: 16500,
        stock: 5,
        lowStockThreshold: 2,
        isAvailable: true,
        image: 'https://images.unsplash.com/photo-1587280501635-68a0e82cd5ff?w=400&auto=format&fit=crop&q=80',
        description: 'Head-heavy power smash badminton racket for singles and doubles offense.',
      },

      // Canteen & Cafe Menu
      {
        name: 'Whey Isolate Protein Recovery Shake (Belgian Choc)',
        type: 'canteen',
        category: 'Beverages',
        price: 220,
        stock: 90,
        lowStockThreshold: 15,
        isAvailable: true,
        image: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=400&auto=format&fit=crop&q=80',
        description: '30g ultra-filtered whey isolate, organic almond milk, and raw cacao.',
      },
      {
        name: 'Grilled Herb Chicken & Avocado Power Wrap',
        type: 'canteen',
        category: 'Meals',
        price: 290,
        stock: 45,
        lowStockThreshold: 10,
        isAvailable: true,
        image: '/images/menu/chicken-avocado-wrap.svg',
        description: 'Rosemary grilled breast, Hass avocado, baby spinach, Greek yogurt dressing.',
      },
      {
        name: 'Wood-Fired Truffle Mushroom & Basil Pizza',
        type: 'canteen',
        category: 'Meals',
        price: 450,
        stock: 35,
        lowStockThreshold: 8,
        isAvailable: true,
        image: '/images/menu/truffle-mushroom-pizza.svg',
        description: 'Sourdough crust, fresh Fior di Latte mozzarella, Portobello mushrooms, black truffle oil.',
      },
      {
        name: 'Freshly Brewed Cold Brew Tonic & Orange Slice',
        type: 'canteen',
        category: 'Beverages',
        price: 180,
        stock: 75,
        lowStockThreshold: 15,
        isAvailable: true,
        image: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=400&auto=format&fit=crop&q=80',
        description: '18-hour steeped single-origin Arabica with botanical tonic water.',
      },
      {
        name: 'Mediterranean Quinoa Greek Salad Bowl',
        type: 'canteen',
        category: 'Healthy',
        price: 260,
        stock: 30,
        lowStockThreshold: 5,
        isAvailable: true,
        image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&auto=format&fit=crop&q=80',
        description: 'Organic tri-color quinoa, Kalamata olives, Persian cucumbers, crumbled feta.',
      },
      {
        name: 'Fresh Hydration Electrolyte Coconut Fizz',
        type: 'canteen',
        category: 'Beverages',
        price: 140,
        stock: 120,
        lowStockThreshold: 20,
        isAvailable: true,
        image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=400&auto=format&fit=crop&q=80',
        description: 'Tender coconut water, Himalayan pink salt, fresh lime, sparkling fizz.',
      },
    ]);

    console.log('8. 🪑 Creating Dining Tables...');
    const diningTables = await DiningTable.create([
      {
        tableNumber: 'Table 1',
        capacity: 4,
        section: 'INDOOR_CAFE',
        status: 'AVAILABLE',
        notes: 'Near pastry display counter.',
      },
      {
        tableNumber: 'Table 2',
        capacity: 2,
        section: 'INDOOR_CAFE',
        status: 'AVAILABLE',
        notes: 'Cozy two-seater corner.',
      },
      {
        tableNumber: 'Table 3',
        capacity: 6,
        section: 'INDOOR_CAFE',
        status: 'RESERVED',
        notes: 'Reserved for Junior Academy coaches lunch.',
      },
      {
        tableNumber: 'Table 4',
        capacity: 4,
        section: 'OUTDOOR_TERRACE',
        status: 'OCCUPIED',
        currentCustomer: {
          name: 'Alex Morgan',
          phone: '+91-9898000012',
          memberId: alexMember._id,
        },
        notes: 'Active live bar tab.',
      },
      {
        tableNumber: 'Table 5',
        capacity: 4,
        section: 'OUTDOOR_TERRACE',
        status: 'AVAILABLE',
        notes: 'Overlooking Court 1 Clay Tennis.',
      },
      {
        tableNumber: 'Table 6',
        capacity: 8,
        section: 'OUTDOOR_TERRACE',
        status: 'CLEANING',
        notes: 'Turf team gathering just vacated.',
      },
      {
        tableNumber: 'VIP Lounge 1',
        capacity: 6,
        section: 'VIP_LOUNGE',
        status: 'OCCUPIED',
        currentCustomer: {
          name: 'Meera Deshmukh',
          phone: '+91-9898000014',
          memberId: meeraMember._id,
        },
        notes: 'Platinum member executive lounge.',
      },
      {
        tableNumber: 'VIP Lounge 2',
        capacity: 6,
        section: 'VIP_LOUNGE',
        status: 'AVAILABLE',
        notes: 'Leather recliners with 4K sports streaming screen.',
      },
      {
        tableNumber: 'Courtside Bar High 1',
        capacity: 2,
        section: 'COURTSIDE_BAR',
        status: 'OCCUPIED',
        currentCustomer: {
          name: 'Walk-in Guest',
          phone: '+91-9988112233',
        },
        notes: 'High stool seating directly overlooking Padel Court 1.',
      },
      {
        tableNumber: 'Courtside Bar High 2',
        capacity: 2,
        section: 'COURTSIDE_BAR',
        status: 'AVAILABLE',
        notes: 'Direct bar service.',
      },
    ]);

    console.log('9. 🛍️ Creating Orders in All Situations (Completed, Pending, Preparing, Ready, Cancelled)...');
    const orders = await Order.create([
      // 1. Pro Shop Counter Sale - Completed (Keni Patel)
      {
        member: keniMember._id,
        customerName: 'Keni Patel',
        customerPhone: '+91-9898000011',
        items: [
          {
            product: products[1]._id,
            name: products[1].name,
            quantity: 2,
            price: products[1].price,
          },
          {
            product: products[4]._id,
            name: products[4].name,
            quantity: 1,
            price: products[4].price,
          },
        ],
        type: 'sports',
        subtotal: 5100,
        discount: 765, // Gold 15% discount
        total: 4335,
        fulfillment: 'counter',
        paymentMethod: 'upi',
        paymentStatus: 'paid',
        status: 'completed',
      },
      // 2. Pro Shop Online Order - Ready for Dispatch (Kabir Singhania)
      {
        member: kabirMember._id,
        customerName: 'Kabir Singhania',
        customerPhone: '+91-9898000015',
        deliveryAddress: '55 Sindhu Bhavan Rd, Ahmedabad - 380059',
        items: [
          {
            product: products[2]._id,
            name: products[2].name,
            quantity: 1,
            price: products[2].price,
          },
        ],
        type: 'sports',
        subtotal: 8900,
        discount: 1335,
        total: 7565,
        fulfillment: 'delivery',
        paymentMethod: 'card',
        paymentStatus: 'paid',
        status: 'ready',
      },
      // 3. Pro Shop Online Order - Pending Payment (Ananya Roy)
      {
        member: ananyaMember._id,
        customerName: 'Ananya Roy',
        customerPhone: '+91-9898000019',
        items: [
          {
            product: products[3]._id,
            name: products[3].name,
            quantity: 1,
            price: products[3].price,
          },
        ],
        type: 'sports',
        subtotal: 6500,
        discount: 1300, // Family 20%
        total: 5200,
        fulfillment: 'counter',
        paymentMethod: 'upi',
        paymentStatus: 'pending',
        status: 'pending',
      },
      // 4. Canteen Active Bar Tab (Table 4 - Alex Morgan) - Preparing
      {
        member: alexMember._id,
        customerName: 'Alex Morgan',
        customerPhone: '+91-9898000012',
        items: [
          {
            product: products[7]._id,
            name: products[7].name,
            quantity: 2,
            price: products[7].price,
          },
          {
            product: products[8]._id,
            name: products[8].name,
            quantity: 2,
            price: products[8].price,
          },
          {
            product: products[9]._id,
            name: products[9].name,
            quantity: 1,
            price: products[9].price,
          },
        ],
        type: 'canteen',
        subtotal: 1470,
        discount: 73.5, // Silver 5%
        total: 1396.5,
        fulfillment: 'table',
        tableNumber: 'Table 4',
        isTab: true,
        tabStatus: 'OPEN',
        paymentMethod: 'tab',
        paymentStatus: 'pending',
        status: 'preparing',
      },
      // 5. Canteen VIP Lounge Tab (VIP Lounge 1 - Meera Deshmukh) - Ready
      {
        member: meeraMember._id,
        customerName: 'Meera Deshmukh',
        customerPhone: '+91-9898000014',
        items: [
          {
            product: products[10]._id,
            name: products[10].name,
            quantity: 2,
            price: products[10].price,
          },
          {
            product: products[11]._id,
            name: products[11].name,
            quantity: 1,
            price: products[11].price,
          },
        ],
        type: 'canteen',
        subtotal: 620,
        discount: 124, // Platinum 20%
        total: 496,
        fulfillment: 'table',
        tableNumber: 'VIP Lounge 1',
        isTab: true,
        tabStatus: 'OPEN',
        paymentMethod: 'tab',
        paymentStatus: 'pending',
        status: 'ready',
      },
      // 6. Canteen Settled Morning Breakfast - Completed (Sara Mehta)
      {
        member: saraMember._id,
        customerName: 'Sara Mehta',
        customerPhone: '+91-9898000016',
        items: [
          {
            product: products[7]._id,
            name: products[7].name,
            quantity: 1,
            price: products[7].price,
          },
          {
            product: products[10]._id,
            name: products[10].name,
            quantity: 1,
            price: products[10].price,
          },
        ],
        type: 'canteen',
        subtotal: 400,
        discount: 40, // Student 10%
        total: 360,
        fulfillment: 'counter',
        paymentMethod: 'upi',
        paymentStatus: 'paid',
        status: 'completed',
        tabStatus: 'CLOSED',
      },
    ]);

    // Link active orders to tables
    await DiningTable.updateOne({ tableNumber: 'Table 4' }, { activeOrderId: orders[3]._id });
    await DiningTable.updateOne({ tableNumber: 'VIP Lounge 1' }, { activeOrderId: orders[4]._id });

    console.log('10. 📦 Creating Inventory Stock Transactions...');
    await InventoryTransaction.create([
      {
        product: products[0]._id,
        type: 'PURCHASE',
        quantity: 10,
        previousStock: 0,
        newStock: 10,
        supplier: 'Wilson Sports India Dist. Pvt Ltd',
        invoiceNumber: 'INV-WIL-8821',
        adjustmentType: 'RECEIVED',
        notes: 'Consignment received for Autumn 2026 season.',
        performedBy: shopUser._id,
      },
      {
        product: products[1]._id,
        type: 'PURCHASE',
        quantity: 200,
        previousStock: 0,
        newStock: 200,
        supplier: 'Wilson Sports India Dist. Pvt Ltd',
        invoiceNumber: 'INV-WIL-8821',
        adjustmentType: 'RECEIVED',
        notes: 'Championship ball cartons delivery.',
        performedBy: shopUser._id,
      },
      {
        product: products[5]._id,
        type: 'DAMAGE',
        quantity: -1,
        previousStock: 3,
        newStock: 2,
        adjustmentType: 'DAMAGED',
        notes: 'Frame micro-fracture found on display unit.',
        performedBy: shopUser._id,
      },
      {
        product: products[1]._id,
        type: 'COUNTER_SALE',
        quantity: -2,
        previousStock: 152,
        newStock: 150,
        adjustmentType: 'MANUAL',
        referenceOrder: orders[0]._id,
        notes: 'Sold at counter to Keni Patel (Gold member).',
        performedBy: shopUser._id,
      },
    ]);

    console.log('11. 💰 Creating Central Unified Payments & Invoices...');
    // Seed Payments across all 4 purposes and methods
    await Payment.create([
      // Membership Payments
      {
        user: keniMember._id,
        customerName: 'Keni Patel',
        amount: 12000,
        paymentMethod: 'UPI',
        purpose: 'MEMBERSHIP',
        purposeRef: 'Membership',
        referenceId: memberships[0]._id,
        status: 'PAID',
        transactionId: `TXN-${Date.now() - 500000}-101`,
        paidAt: new Date(Date.now() - 500000),
        notes: 'Gold Plan Annual Subscription',
      },
      {
        user: alexMember._id,
        customerName: 'Alex Morgan',
        amount: 8000,
        paymentMethod: 'CARD',
        purpose: 'MEMBERSHIP',
        purposeRef: 'Membership',
        referenceId: memberships[1]._id,
        status: 'PAID',
        transactionId: `TXN-${Date.now() - 450000}-102`,
        paidAt: new Date(Date.now() - 450000),
        notes: 'Silver Plan Annual Subscription',
      },
      {
        user: meeraMember._id,
        customerName: 'Meera Deshmukh',
        amount: 24000,
        paymentMethod: 'CARD',
        purpose: 'MEMBERSHIP',
        purposeRef: 'Membership',
        referenceId: memberships[3]._id,
        status: 'PAID',
        transactionId: `TXN-${Date.now() - 400000}-103`,
        paidAt: new Date(Date.now() - 400000),
        notes: 'Platinum VIP Plan Annual Subscription',
      },
      {
        user: rohanMember._id,
        customerName: 'Rohan Gupta',
        amount: 5000,
        paymentMethod: 'UPI',
        purpose: 'MEMBERSHIP',
        purposeRef: 'Membership',
        referenceId: memberships[2]._id,
        status: 'PAID',
        transactionId: `TXN-${Date.now() - 350000}-104`,
        paidAt: new Date(Date.now() - 350000),
        notes: 'Junior Academy Annual Subscription',
      },
      {
        user: ananyaMember._id,
        customerName: 'Ananya Roy',
        amount: 35000,
        paymentMethod: 'CARD',
        purpose: 'MEMBERSHIP',
        purposeRef: 'Membership',
        referenceId: memberships[8]._id,
        status: 'PAID',
        transactionId: `TXN-${Date.now() - 300000}-105`,
        paidAt: new Date(Date.now() - 300000),
        notes: 'Family All-Inclusive Annual Subscription',
      },

      // Court Booking Payments
      {
        user: keniMember._id,
        customerName: 'Keni Patel',
        amount: 480,
        paymentMethod: 'UPI',
        purpose: 'COURT_BOOKING',
        purposeRef: 'Booking',
        referenceId: bookings[0]._id,
        status: 'PAID',
        transactionId: `TXN-${Date.now() - 250000}-201`,
        paidAt: new Date(Date.now() - 250000),
        notes: 'Center Court morning match fee',
      },
      {
        user: alexMember._id,
        customerName: 'Alex Morgan',
        amount: 585,
        paymentMethod: 'UPI',
        purpose: 'COURT_BOOKING',
        purposeRef: 'Booking',
        referenceId: bookings[2]._id,
        status: 'PAID',
        transactionId: `TXN-${Date.now() - 200000}-202`,
        paidAt: new Date(Date.now() - 200000),
        notes: 'Padel Panoramic Court 1 reservation',
      },
      {
        customerName: 'Sameer Desai',
        amount: 1800,
        paymentMethod: 'CARD',
        purpose: 'COURT_BOOKING',
        purposeRef: 'Booking',
        referenceId: bookings[3]._id,
        status: 'PAID',
        transactionId: `TXN-${Date.now() - 150000}-203`,
        paidAt: new Date(Date.now() - 150000),
        notes: 'Box Cricket Arena counter booking',
      },
      {
        customerName: 'Dr. Harshil Shah',
        amount: 650,
        paymentMethod: 'CASH',
        purpose: 'COURT_BOOKING',
        purposeRef: 'Booking',
        referenceId: bookings[4]._id,
        status: 'PAID',
        transactionId: `TXN-${Date.now() - 100000}-204`,
        paidAt: new Date(Date.now() - 100000),
        notes: 'Badminton Court 1 phone booking cash collection',
      },

      // Sports Shop Payments
      {
        user: keniMember._id,
        customerName: 'Keni Patel',
        amount: 4335,
        paymentMethod: 'UPI',
        purpose: 'SHOP_ORDER',
        purposeRef: 'Order',
        referenceId: orders[0]._id,
        status: 'PAID',
        transactionId: `TXN-${Date.now() - 80000}-301`,
        paidAt: new Date(Date.now() - 80000),
        notes: 'Counter POS sale for tennis balls and strings',
      },
      {
        user: kabirMember._id,
        customerName: 'Kabir Singhania',
        amount: 7565,
        paymentMethod: 'CARD',
        purpose: 'SHOP_ORDER',
        purposeRef: 'Order',
        referenceId: orders[1]._id,
        status: 'PAID',
        transactionId: `TXN-${Date.now() - 60000}-302`,
        paidAt: new Date(Date.now() - 60000),
        notes: 'Online pro shop gear order delivery',
      },

      // Canteen Payments
      {
        user: saraMember._id,
        customerName: 'Sara Mehta',
        amount: 360,
        paymentMethod: 'UPI',
        purpose: 'CANTEEN_ORDER',
        purposeRef: 'Order',
        referenceId: orders[5]._id,
        status: 'PAID',
        transactionId: `TXN-${Date.now() - 40000}-401`,
        paidAt: new Date(Date.now() - 40000),
        notes: 'Counter cafe shake and cold brew payment',
      },
    ]);

    await Invoice.create([
      {
        invoiceNumber: 'INV-2026-1001',
        user: keniMember._id,
        customerName: 'Keni Patel',
        customerEmail: 'keni@championsclub.com',
        customerPhone: '+91-9898000011',
        type: 'MEMBERSHIP',
        items: [
          {
            description: 'Annual Gold Membership Tier (365 Days Access)',
            quantity: 1,
            unitPrice: 12000,
            amount: 12000,
          },
        ],
        subtotal: 12000,
        totalAmount: 12000,
        paymentStatus: 'PAID',
        paymentMethod: 'UPI',
        paidDate: new Date(),
      },
      {
        invoiceNumber: 'INV-2026-1002',
        user: meeraMember._id,
        customerName: 'Meera Deshmukh',
        customerEmail: 'meera.d@championsclub.com',
        customerPhone: '+91-9898000014',
        type: 'MEMBERSHIP',
        items: [
          {
            description: 'Annual Platinum VIP Membership Tier (365 Days All-Inclusive)',
            quantity: 1,
            unitPrice: 24000,
            amount: 24000,
          },
        ],
        subtotal: 24000,
        totalAmount: 24000,
        paymentStatus: 'PAID',
        paymentMethod: 'CARD',
        paidDate: new Date(),
      },
      {
        invoiceNumber: 'INV-2026-1003',
        user: keniMember._id,
        customerName: 'Keni Patel',
        customerEmail: 'keni@championsclub.com',
        customerPhone: '+91-9898000011',
        type: 'SHOP',
        items: [
          {
            description: 'Wilson US Open Championship Tennis Balls (Can of 3)',
            quantity: 2,
            unitPrice: 450,
            amount: 900,
          },
          {
            description: 'Yonex BG65 Titanium Badminton String Reel (200m)',
            quantity: 1,
            unitPrice: 4200,
            amount: 4200,
          },
        ],
        subtotal: 5100,
        discount: 765,
        totalAmount: 4335,
        paymentStatus: 'PAID',
        paymentMethod: 'UPI',
        paidDate: new Date(),
      },
    ]);

    await Expense.create([
      {
        title: 'Center Court Red Clay Top Dressing & Rolling Refurbishment',
        category: 'MAINTENANCE',
        amount: 32000,
        date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
        paymentMethod: 'BANK_TRANSFER',
        vendor: 'Acro Surfaces India',
        recordedBy: owner._id,
        notes: 'Pre-tournament court conditioning and line painting.',
      },
      {
        title: 'Monthly High-Mast Arena Floodlight Electricity Bill',
        category: 'UTILITIES',
        amount: 48500,
        date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
        paymentMethod: 'BANK_TRANSFER',
        vendor: 'Torrent Power Ltd',
        recordedBy: owner._id,
        notes: 'Commercial sports facility monthly power consumption.',
      },
      {
        title: 'Spinshot Tennis Ball Machine Spare Battery & Wheels',
        category: 'EQUIPMENT',
        amount: 14500,
        date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
        paymentMethod: 'CARD',
        vendor: 'Pro Tennis Gear Hub',
        recordedBy: coachUser._id,
        notes: 'Ball machine maintenance for morning coaching academy.',
      },
      {
        title: 'Sports Nutrition, Whey & Cold Brew Kitchen Supplies Restock',
        category: 'SUPPLIES',
        amount: 22000,
        date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
        paymentMethod: 'UPI',
        vendor: 'Metro Wholesale Cash & Carry',
        recordedBy: canteenUser._id,
        notes: 'Stock for cafeteria shakes, avocado wraps, and artisanal beans.',
      },
      {
        title: 'Staff Monthly Payroll (All Departments)',
        category: 'SALARY',
        amount: 168000,
        date: new Date('2026-09-30'),
        paymentMethod: 'BANK_TRANSFER',
        vendor: 'Internal HR',
        recordedBy: owner._id,
        notes: 'September month salary disbursement.',
      },
    ]);

    console.log('12. 🎯 Creating CRM Leads, Projects & Operations Tasks...');
    await Lead.create([
      {
        name: 'Neha Kapoor',
        email: 'neha.k@gmail.com',
        phone: '+91-9876543210',
        interestedSport: 'PADEL',
        interestedPlan: 'GOLD',
        message: 'Looking for evening weekend padel slots and beginner coaching programs.',
        status: 'TRIAL_BOOKED',
        assignedStaff: frontDeskUser._id,
        notes: 'Complimentary 30-min trial arranged on Padel Court 2.',
      },
      {
        name: 'Tarun Mehra',
        email: 'tarun.m@outlook.com',
        phone: '+91-9876543211',
        interestedSport: 'CRICKET',
        interestedPlan: 'SILVER',
        message: 'Corporate weekend tournament turf booking query for 40 employees.',
        status: 'CONTACTED',
        assignedStaff: frontDeskUser._id,
        notes: 'Sent turf rate card and catering options.',
      },
      {
        name: 'Dr. Siddharth Varma',
        email: 'dr.siddharth@gmail.com',
        phone: '+91-9876543212',
        interestedSport: 'TENNIS',
        interestedPlan: 'PLATINUM',
        message: 'Inquiring about executive VIP locker room and personal coaching slots.',
        status: 'NEW',
        assignedStaff: null,
      },
    ]);

    const project = await Project.create({
      title: 'Grand Autumn Padel & Tennis Championship 2026',
      description: 'Annual inter-club 3-day sports championship with prize pool, live streaming, sponsor exhibition booths and gourmet food court.',
      category: 'Events & Tournaments',
      status: 'in-progress',
      priority: 'high',
      budget: 350000,
      progress: 65,
      deadline: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000),
      owner: owner._id,
      members: [frontDeskUser._id, shopUser._id, canteenUser._id, coachUser._id],
      tags: ['Tournament', 'Sponsorship', 'Padel', 'Tennis'],
    });

    await Task.create([
      {
        title: 'Confirm Wilson Match Ball Sponsorship & 500 Can Delivery',
        description: 'Ensure official match ball consignment arrives at least 5 days prior to tournament start.',
        project: project._id,
        assignee: shopUser._id,
        status: 'in-progress',
        priority: 'high',
        dueDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
        tags: ['Inventory', 'Wilson', 'Sponsorship'],
      },
      {
        title: 'Finalize Tournament Special Food & Smoothie Menu',
        description: 'Design high-protein athlete lunch boxes and courtside hydration stations.',
        project: project._id,
        assignee: canteenUser._id,
        status: 'in-progress',
        priority: 'medium',
        dueDate: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000),
        tags: ['Canteen', 'Catering'],
      },
      {
        title: 'Publish Fixtures & Send Schedule to 64 Registered Players',
        description: 'Generate draw bracket on club portal and notify all registered doubles pairs.',
        project: project._id,
        assignee: coachUser._id,
        status: 'todo',
        priority: 'urgent',
        dueDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
        tags: ['Draws', 'Scheduling'],
      },
    ]);

    console.log('13. ⚙️ Creating Club Settings Singleton...');
    await ClubSetting.create({
      clubName: 'The Champions Sports Club',
      contactEmail: 'support@championsclub.com',
      contactPhone: '+91 98765 43210',
      address: '100 Olympic Boulevard, Sports Complex, SG Highway, Ahmedabad, Gujarat',
      sessionDurationMinutes: 60,
      slotIntervalMinutes: 30,
      membershipGracePeriodDays: 7,
      taxRatePercent: 18,
      currencySymbol: '₹',
      allowWalkInBookings: true,
    });

    console.log('14. 🔔 Creating Notifications, Activities & Audit Logs...');
    await Notification.create([
      {
        recipient: owner._id,
        title: 'New Platinum VIP Subscription',
        message: 'Meera Deshmukh activated Platinum VIP Membership plan (₹24,000 paid).',
        type: 'success',
        link: '/manager/members',
      },
      {
        recipient: frontDeskUser._id,
        title: 'Court 2 Match In-Progress',
        message: 'Meera Deshmukh checked in at Court 2 Synthetic Hard Tennis.',
        type: 'info',
        link: '/staff/front-desk?tab=courts',
      },
      {
        recipient: shopUser._id,
        title: 'Low Stock Alert: Bullpadel Vertex 04',
        message: 'Stock level is 2 rackets remaining (threshold: 3). Reorder advised.',
        type: 'warning',
        link: '/staff/shop?tab=inventory',
      },
      {
        recipient: canteenUser._id,
        title: 'Active Tab on Table 4',
        message: 'Alex Morgan opened an active bar tab (₹1,396.50).',
        type: 'info',
        link: '/staff/canteen?tab=orders',
      },
      {
        recipient: keniMember._id,
        title: 'Booking Confirmed for Center Court',
        message: 'Your slot today at 20:00 - 21:00 is confirmed. See you on the clay!',
        type: 'success',
        link: '/courts',
      },
    ]);

    await Activity.create([
      {
        user: owner._id,
        action: 'System Database Seeded & Initialized',
        entity: 'System',
        metadata: { info: 'Complete multi-tier member, staff, court, shop, canteen, and payment data seeded.' },
      },
      {
        user: keniMember._id,
        action: 'Court Slot Booked',
        entity: 'Booking',
        metadata: { court: 'Center Court - Clay Tennis', time: '20:00 - 21:00' },
      },
      {
        user: frontDeskUser._id,
        action: 'Member Checked In',
        entity: 'Booking',
        metadata: { court: 'Court 2 - Synthetic Hard Tennis', member: 'Meera Deshmukh' },
      },
      {
        user: alexMember._id,
        action: 'Opened Bar Tab',
        entity: 'Order',
        metadata: { table: 'Table 4', total: 1396.5 },
      },
      {
        user: shopUser._id,
        action: 'Processed Counter Sale',
        entity: 'Order',
        metadata: { invoice: 'INV-2026-1003', amount: 4335 },
      },
    ]);

    await AuditLog.create([
      {
        user: owner._id,
        action: 'ROLE_UPDATE',
        entity: 'User',
        entityId: coachUser._id.toString(),
        ipAddress: '192.168.1.1',
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/128.0',
        details: { role: 'STAFF', department: 'FRONT_DESK', title: 'Head Coach' },
      },
      {
        user: frontDeskUser._id,
        action: 'WALK_IN_BOOKING_CREATED',
        entity: 'Booking',
        ipAddress: '192.168.1.15',
        userAgent: 'ChampionsClubPOS/1.0 FrontDesk',
        details: { court: 'Floodlit Box Cricket Arena', customer: 'Sameer Desai', amount: 1800 },
      },
      {
        user: owner._id,
        action: 'PAYROLL_APPROVED_AND_PAID',
        entity: 'Payroll',
        ipAddress: '192.168.1.1',
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
        details: { month: 'September 2026', totalStaffPaid: 5, totalDisbursed: 168000 },
      },
    ]);

    console.log('========================================================================');
    console.log('🏆 THE CHAMPIONS CLUB: COMPLETE REALISTIC SYSTEM DATA SEEDED SUCCESSFULLY!');
    console.log('========================================================================');
    console.log('🔑 Operational Login Credentials:');
    console.log('👑 Club Manager:           owner@championsclub.com          | Owner@123');
    console.log('🎾 Front Desk (Staff):     frontdesk@championsclub.com      | Staff@123');
    console.log('🛍️ Sports Shop (Staff):   shop@championsclub.com           | Staff@123');
    console.log('☕ Canteen & Bar (Staff):  canteen@championsclub.com        | Staff@123');
    console.log('🎾 Head Coach (Staff):     coach.dharmesh@championsclub.com | Staff@123');
    console.log('🥇 Member (Platinum VIP):  meera.d@championsclub.com        | Member@123');
    console.log('🥇 Member (Gold Tier):     keni@championsclub.com           | Member@123');
    console.log('🥈 Member (Silver Tier):   alex@championsclub.com           | Member@123');
    console.log('🥉 Member (Junior Tier):   junior@championsclub.com         | Member@123');
    console.log('🏸 Member (Corporate):     kabir.s@championsclub.com        | Member@123');
    console.log('🎓 Member (Student Tier):  sara.m@championsclub.com         | Member@123');
    console.log('👨‍👩‍👦 Member (Family Tier):   ananya.r@championsclub.com       | Member@123');
    console.log('========================================================================');

    process.exit(0);
  } catch (err) {
    console.error('❌ Seeding Error:', err);
    process.exit(1);
  }
};

seedDatabase();
